inputattach: ifdef macro for SERIO_TSC40
SERIO_TSC40 only appears in later kernels and breaks builds based on
earlier kernels with the following error:

inputattach.c:655:2: error: 'SERIO_TSC40' undeclared here (not in a function)

Fix this by bracketing section with an ifdef.

Signed-off-by: Kyle Manna <kyle.manna@fuel7.com>
Signed-off-by: Stephen Kitt <steve@sk2.org>